### ISSUE TITLE
Seems like the wrong SDL version is vendored.

### ISSUE THREAD

**Issue by dbriemann** [tanema/amore#12]
Just wanted to play around with your library. However after installing the dependencies with glide and trying to build the examples I see a lot of errors

```
# github.com/tanema/amore/vendor/github.com/tanema/amore/joystick
../../amore/vendor/github.com/tanema/amore/joystick/joystick.go:36:50: cannot use sdl.JoystickID(joystick.id) (type sdl.JoystickID) as type int in argument to sdl.JoystickOpen
../../amore/vendor/github.com/tanema/amore/joystick/joystick.go:68:48: joystick.stick.GetAttached undefined (type *sdl.Joystick has no field or method GetAttached)
../../amore/vendor/github.com/tanema/amore/joystick/joystick.go:73:49: joystick.stick.GetGUID undefined (type *sdl.Joystick has no field or method GetGUID)
../../amore/vendor/github.com/tanema/amore/joystick/joystick.go:98:23: joystick.stick.GetButton undefined (type *sdl.Joystick has no field or method GetButton)
../../amore/vendor/github.com/tanema/amore/joystick/joystick.go:131:40: joystick.stick.GetAxis undefined (type *sdl.Joystick has no field or method GetAxis)
../../amore/vendor/github.com/tanema/amore/joystick/joystick.go:144:54: joystick.stick.GetAxis undefined (type *sdl.Joystick has no field or method GetAxis)
../../amore/vendor/github.com/tanema/amore/joystick/joystick.go:156:23: joystick.stick.GetHat undefined (type *sdl.Joystick has no field or method GetHat)
../../amore/vendor/github.com/tanema/amore/joystick/joystick.go:165:30: joystick.controller.GetAxis undefined (type *sdl.GameController has no field or method GetAxis)
../../amore/vendor/github.com/tanema/amore/joystick/joystick.go:176:28: joystick.controller.GetButton undefined (type *sdl.GameController has no field or method GetButton)
../../amore/vendor/github.com/tanema/amore/joystick/joystick.go:251:58: cannot use &joystick.vibration.Effect (type *sdl.HapticEffect) as type sdl.iHapticEffect in argument to joystick.haptic.UpdateEffect:
	*sdl.HapticEffect does not implement sdl.iHapticEffect (missing sdl.cHapticEffect method)
../../amore/vendor/github.com/tanema/amore/joystick/joystick.go:251:58: too many errors
# github.com/tanema/amore/vendor/github.com/tanema/amore/window
../../amore/vendor/github.com/tanema/amore/window/window.go:63:28: too many arguments in call to sdl.GetDesktopDisplayMode
	have (int, *sdl.DisplayMode)
	want (int)
../../amore/vendor/github.com/tanema/amore/window/window.go:83:33: too many arguments in call to sdl.GetDisplayMode
	have (int, number, *sdl.DisplayMode)
	want (int, int)
../../amore/vendor/github.com/tanema/amore/window/window.go:83:33: multiple-value sdl.GetDisplayMode() in single-value context
../../amore/vendor/github.com/tanema/amore/window/window.go:108:23: too many arguments in call to sdl.GetDisplayBounds
	have (int, *sdl.Rect)
	want (int)
../../amore/vendor/github.com/tanema/amore/window/window.go:167:18: undefined: sdl.GLCreateContext
../../amore/vendor/github.com/tanema/amore/window/window.go:244:28: too many arguments in call to sdl.GetDesktopDisplayMode
	have (int, *sdl.DisplayMode)
	want (int)
../../amore/vendor/github.com/tanema/amore/window/window.go:261:10: undefined: sdl.GLGetDrawableSize
../../amore/vendor/github.com/tanema/amore/window/window.go:271:21: too many arguments in call to sdl.GetDisplayMode
	have (int, int, *sdl.DisplayMode)
	want (int, int)
../../amore/vendor/github.com/tanema/amore/window/window.go:332:2: undefined: sdl.GLSwapWindow
../../amore/vendor/github.com/tanema/amore/window/window.go:395:23: multiple-value sdl.ShowCursor() in single-value context
../../amore/vendor/github.com/tanema/amore/window/window.go:395:23: too many errors
```

My guess is that the wrong version of go-sdl2 is vendored?

**Comment by tanema** [comment]
Did you use glide? I just used `glide get` and it worked fine. But I used the spread operator and got all those errors. I will need to update the SDL code to work with the go-sdl2 master branch.

**Comment by dbriemann** [comment]
Yes I used Glide. I just tried again:

- deleted vendor folder
- used `glide get github.com/tanema/amore`

After that the glide files are changed.. here is an excerpt from git diff (glide.lock):
```
 - name: github.com/veandco/go-sdl2
-  version: d1ebfcf49872383b6533ee2a51ae478ae3999c0c
+  version: 4dfc7fa236d8f901a7976006e2a209fc6e743f24
```

I don't know really know glide because I usually use dep. Maybe I am doing something wrong?

edit: copied wrong part of glide.lock :) fixed now
edit2: I just realised that my last edit may have sounded like I managed to make it run but it was only related to this comment. Just in case .. if I would have found a solution I would have mentioned it :)

**Comment by tanema** [comment]
I am updating the sdl requirement but am stuck on one issue here: https://github.com/veandco/go-sdl2/issues/331 They are usually quite responsive so I should have this fixed soon 👍

**Comment by tanema** [comment]
It seems my PR did not fix it

**Comment by tanema** [comment]
Okay I just pushed to master with dep tooling. You should be able to run it now.

**Comment by dbriemann** [comment]
It works now thanks! However I think it is because you adjusted it for the newest SDL version.

I don't see any dep files included. Maybe you forgot to commit them?

**Comment by tanema** [comment]
yup, you were right I added them now.
